"""init

Revision ID: 06c7b2314541
Revises: 
Create Date: 2023-04-07 14:30:06.233959

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '06c7b2314541'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('detail_link', sa.String(length=150), nullable=True),
    sa.Column('release_date', sa.DATE(), nullable=True),
    sa.Column('num_players', sa.String(length=50), nullable=True),
    sa.Column('meta_score', sa.Integer(), nullable=True),
    sa.Column('user_score', sa.Float(), nullable=True),
    sa.Column('image_link', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=1500), nullable=True),
    sa.PrimaryKeyConstraint('id', 'name')
    )
    op.create_index(op.f('ix_Game_id'), 'Game', ['id'], unique=False)
    op.create_index(op.f('ix_Game_name'), 'Game', ['name'], unique=False)
    op.create_table('developer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', 'name')
    )
    op.create_index(op.f('ix_developer_id'), 'developer', ['id'], unique=False)
    op.create_index(op.f('ix_developer_name'), 'developer', ['name'], unique=False)
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', 'name')
    )
    op.create_index(op.f('ix_genre_id'), 'genre', ['id'], unique=False)
    op.create_index(op.f('ix_genre_name'), 'genre', ['name'], unique=False)
    op.create_table('platform',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', 'name')
    )
    op.create_index(op.f('ix_platform_id'), 'platform', ['id'], unique=False)
    op.create_index(op.f('ix_platform_name'), 'platform', ['name'], unique=False)
    op.create_table('publisher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', 'name')
    )
    op.create_index(op.f('ix_publisher_id'), 'publisher', ['id'], unique=False)
    op.create_index(op.f('ix_publisher_name'), 'publisher', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publisher_name'), table_name='publisher')
    op.drop_index(op.f('ix_publisher_id'), table_name='publisher')
    op.drop_table('publisher')
    op.drop_index(op.f('ix_platform_name'), table_name='platform')
    op.drop_index(op.f('ix_platform_id'), table_name='platform')
    op.drop_table('platform')
    op.drop_index(op.f('ix_genre_name'), table_name='genre')
    op.drop_index(op.f('ix_genre_id'), table_name='genre')
    op.drop_table('genre')
    op.drop_index(op.f('ix_developer_name'), table_name='developer')
    op.drop_index(op.f('ix_developer_id'), table_name='developer')
    op.drop_table('developer')
    op.drop_index(op.f('ix_Game_name'), table_name='Game')
    op.drop_index(op.f('ix_Game_id'), table_name='Game')
    op.drop_table('Game')
    # ### end Alembic commands ###
